#!/bin/bash
set -e

# Activate the local virtual environment generated by Oryx
source antenv/bin/activate

echo "Running database migrations..."
flask db upgrade

echo "Starting gunicorn..."
exec gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120
